spin_manifest_version = 2

[application]
authors = ["Glenn Lewis"]
description = "A simple Spin application written in MoonBit."
name = "hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "hello-world.wasm"
[component.hello.build]
command = "moon build --target wasm && cp ../../target/wasm/release/build/examples/hello-world/hello-world.wasm ."
# command = "moon build --target wasm-gc && cp ../../target/wasm-gc/release/build/examples/hello-world/hello-world.wasm ."
