spin_manifest_version = 2

[application]
authors = ["Glenn Lewis"]
description = "A simple Spin application written in MoonBit."
name = "hello-world"
version = "0.1.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "hello.wasm"
[component.hello.build]
command = "moon build --target wasm-gc"
