spin_manifest_version = 2

[application]
authors = ["Glenn Lewis"]
description = "A simple Spin application written in MoonBit."
name = "variables"
version = "0.1.0"

[variables]
secret_var_name = { required = true }

[[trigger.http]]
component = "variables"
route = "/..."

[component.variables]
source = "variables.wasm"

[component.variables.build]
command = "moon build --target wasm && wasm-tools component embed ../../wit ../../target/wasm/release/build/examples/variables/variables.wasm -o variables.wasm --encoding utf16 -w http-trigger && wasm-tools component new variables.wasm -o variables.wasm"
watch = ["**/*.mbt"]

[component.variables.variables]
secret_var_name = "{{ secret_var_name }}"
